### ISSUE TITLE
mm-mac2ipv4.sh incorrect does multiple hex2dec conversions

### ISSUE THREAD

**Issue by westbywest** [pittmesh/ip-calculator#28]
https://github.com/pittmesh/ip-calculator/blob/954e2e39cce62a66f687337f42e0d82a8725f6f9/mm-mac2ipv4.sh#L90
https://github.com/pittmesh/ip-calculator/blob/954e2e39cce62a66f687337f42e0d82a8725f6f9/mm-mac2ipv4.sh#L91
The printf lines above already convert hex to decimal.  This arithmetic yields incorrect values.

**Comment by colindean** [comment]
What was your reason for closing? Is this not actually occurring?

**Comment by westbywest** [comment]
See issue #29.  The arithmetic for modulo + offset is presumably by design.  Underlying problem affecting me was a discrepancy in order of operations.
